services:
  mongo:
    image: mongo:8.0.4
    container_name: mongo_db
    restart: always
    ports:
     - 27017:27017
    volumes: 
     - ./mongoData:/data/db
     
  mysql:
    image: mysql:9.2.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
     - 3306:3306
    volumes:
     - ./mysqlData:/var/lib/mysql
     
  phpmyadmin:
    image: phpmyadmin
    container_name: web_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
